# Generated by Django 3.0.2 on 2020-02-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200203_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.URLField(default='https://picsum.photos/120/90'),
            preserve_default=False,
        ),
    ]
