name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
    env:
      working-directory: frontend
    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ matrix.node-version }}'
      - run: npm ci
        working-directory: '${{env.working-directory}}'
      - run: npm run build --if-present
        working-directory: '${{env.working-directory}}'
      - run: npm test
        working-directory: '${{env.working-directory}}'
        env:
          CI: true
